import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/Header"; 
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const data = new Date()
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
return (
    <html lang="en">
      <body className='flex flex-col justify-center gap-5 p-20 items-center min-h-screen'>
        
       <Header />
        
        <main className="bg-blue-200 p-5 rounded-3xl max-w-8xl w-full min-h-[70vh] shadow-xl">
          {children}
        </main>
        
        <footer className="text-gray-700 text-sm font-medium">DIW {data.getFullYear()}</footer>

      </body>
    </html>
  );
}
